# Site settings
title: Crowdliness
email: X@crowdliness.org
description: ... something so immediately compelling, inspiringly raw and nakedly fascinating that it will attract a crowd. Or flies.
twitter_username: Crowdliness
github_username:  Crowdliness

# Build settings
markdown: kramdown
